---
# Which port the server should listen on.
port: 8081

# Which content types the static server should use. 'if' is a regex that's
# matched against the filename; if it matches, the content type in 'then'
# is sent.
content-types:
  - if: .*\.html?
    then: text/html; charset=utf-8
  - if: .*\.json
    then: application/json; charset=utf-8
  - if: .*\.js
    then: text/javascript; charset=utf-8
  - if: .*\.css
    then: text/css; charset=utf-8
  - if: .*\.svg
    then: image/svg+xml; charset=utf-8
  - if: .*\.png
    then: image/png
  - if: .*\.jpe?g
    then: image/jpeg
  - if: .*\.gif
    then: image/gif
  - if: .*\.ico
    then: image/vnd.microsoft.icon

custom-structures:
  example:
    paused:
      key: frame.paused
    time:
      key: game.time
    engine:
      key: truck.engine.enabled

input:
  binary:
    engine: Toggle engine power
