#pragma once

#include <chrono>
#include <map>
#include <memory>
#include <mutex>
#include <queue>
#include <string>
#include <vector>

#include <scssdk_input.h>
#include <scssdk_input_device.h>
#include <scssdk_input_event.h>

#include <nlohmann/json.hpp>

#include "api.h"
#include "server/config.h"

/// Singleton class that manages input states in the game thread.
class Input {
private:
    /// State logic for an input channel. Manages things like button presses.
    class Channel {

        /// Whether this is a boolean or floating-point channel.
        const InputChannelType channel_type;

        /// Counter that is incremented for every API request to press this
        /// button, and decremented whenever update requests a 0.0 on behalf of
        /// this after the previous state was 1.0.
        size_t button_presses_pending = 0;

        /// Current state of the input. For boolean inputs, the threshold is
        /// 0.5.
        float state = 0.0f;

        /// The state of the input as far as the game knows.
        float game_state = 0.0f;

    public:
        /// Name of the channel.
        const std::string name;

        /// Channel constructor.
        Channel(std::string name, InputChannelType channel_type);

        /// Called when the game activates our input device and/or we haven't
        /// been queried for at least a second, to prevent old button clicks
        /// from being sent to the game unexpectedly.
        void reset_press_count();

        /// Called whenever the game calls us for input updates. Returns whether
        /// this channel wants to be updated, in which case it must write the
        /// desired update to the given event buffer. The channel index is NOT
        /// written here, because the channel instance doesn't know it.
        bool get_event(scs_input_event_t &event);

        /// Records input from the server into this input channel.
        void send_input(float action);
    };

    /// Maps semantic input names to the index we registered them with. This is
    /// expected not to be mutated anymore once any threading begins; it is not
    /// protected by a mutex.
    std::map<std::string, std::pair<scs_u32_t, InputChannelType>> channel_map;

    /// Vector of all the input channel handlers.
    std::vector<Channel> channels;

    /// Input device list passed to the game. The docs for the input device
    /// registration function specify that "the structure is fully processed
    /// during the call," but just to be sure, we only free this when the input
    /// side of the plugin is unloaded.
    std::vector<scs_input_device_input_t> game_input_descriptors = {};

    /// As above, for the toplevel descriptor  struct.
    scs_input_device_t game_device_descriptor = {};

    /// Index that keeps track of which channels we've polled in the current
    /// frame.
    scs_u32_t poll_index = 0;

    /// When the last frame was started.
    std::chrono::system_clock::time_point last_frame;

    /// Input event commands generated by the server.
    struct InputEvent {

        /// Index of the channel that is to be manipulated.
        scs_u32_t channel;

        /// What to do with the channel. A value between 0 and 1 inclusive
        /// sets the current value. A negative value is treated like a button
        /// press.
        float action;
    };

    /// Queue of events from the server thread.
    std::queue<InputEvent> event_queue;

    /// The mutex guarding the event queue.
    std::mutex event_queue_mutex;

    /// Called at the start of a frame. activated is set when this is the first
    /// frame after the game (re)activated our input device.
    void start_of_frame(bool activated);

    /// Called whenever the game calls us for input updates. Returns whether any
    /// channel still wants to be updated, in which case the event buffer is
    /// written.
    bool get_event(scs_input_event_t &event);

    /// Current input instance used by the static callbacks from the SCS
    /// API.
    static std::unique_ptr<Input> instance;

    /// Called when the game is asking us for event input.
    static SCSAPI_RESULT scs_input_event(
        scs_input_event_t *event_info, scs_u32_t flags, scs_context_t context
    );

    /// Registers a channel. This must only be done in the constructor; the
    /// structures it affects are assumed immutable after construction.
    void register_channel(
        const char *name, const char *display_name, InputChannelType type
    );

    /// Constructor.
    Input(
        const scs_input_init_params_v100_t *init_params,
        const InputChannelDescriptors &descriptors
    );

public:
    /// Called from the SCS API input initialization hook to initialize the
    /// input logic.
    static void init(
        const scs_input_init_params_v100_t *init_params,
        const InputChannelDescriptors &descriptors
    );

    /// Called from the SCS API input shutdown hook to clean up memory.
    static void shutdown();

    /// Thread-safe function for sending input to the game. If new_state is
    /// not specified, the input logic will simulate a button press. Returns
    /// whether the input handler and the channel actually exist.
    static bool send_input(
        const std::string &channel, float new_state = API_INPUT_VALUE_PRESS
    );

    /// Thread-safe function that describes the available inputs and their type.
    static nlohmann::json get_inputs();

    /// Runs an API query. Returns null iff the query is not for the input
    /// subsystem.
    static nlohmann::json run_query(const std::vector<std::string> &query);
};
