---
name: CMake

on:
  pull_request:
  push:
    branches: [main]
    tags: v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v6
        with:
          # We need full history to allow CMake to determine the project
          # version from git.
          fetch-depth: 0
          fetch-tags: true

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Generate bundled files
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir -p ${{github.workspace}}/gamedir/plugins
          cp ${{github.workspace}}/build/libtrucktel.so ${{github.workspace}}/gamedir/plugins
          cd ${{github.workspace}}/gamedir
          ${{github.workspace}}/build/dummy --non-interactive
          rm `find -name log.txt`
          find

      - name: Upload (Linux)
        uses: actions/upload-artifact@v7
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: output-linux
          path: gamedir/plugins/*

      - name: Upload (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v7
        with:
          name: output-windows
          path: build\Release\trucktel.dll

  generate-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - run: |
          cd examples/NuxtTruckTelExample
          npm install
          npm run generate
          mkdir -p example/www
          cp trucktel/config.yaml example
          cp -r .output/public/* example/www

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: output-example
          path: examples/NuxtTruckTelExample/example

  release:
    needs:
      - build
      - generate-example
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: output-windows
          path: build

      - uses: actions/download-artifact@v8
        with:
          name: output-linux
          path: build

      - uses: actions/download-artifact@v8
        with:
          name: output-example
          path: build/trucktel/example

      - name: Build binary release package
        run: |
          cd build
          ls -R
          7z a ../trucktel.zip .

      - name: Make release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release package
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: trucktel.zip
          asset_name: trucktel.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
